### ISSUE TITLE
raster.path

### ISSUE THREAD

**Issue by jblairpdx** [phobson/esri_errata#1]
In errata.md, you state that the fix for raster.path not being the full dataset path is to use `os.path.join(raster.path, raster.name)`. A second fix would be to use `raster.catalogPath`, which is the actual property with the full path.

The path property being terribly-documented also exists for the describe object, which the raster properties mirror: describe.path is documented as "The file path".
https://pro.arcgis.com/en/pro-app/arcpy/functions/describe-object-properties.htm

**Comment by phobson** [comment]
@jblairpdx this is good info! Would you mind creating a pull request?
